# Generated by Django 4.1.3 on 2022-11-28 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userscoresmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserScoresModel',
        ),
    ]
