# Generated by Django 2.0.13 on 2020-09-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScoresModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('hashtag', models.CharField(max_length=100)),
                ('nbscore', models.FloatField()),
                ('nbcohen', models.FloatField()),
                ('svmscore', models.FloatField()),
                ('svmcohen', models.FloatField()),
                ('rfscore', models.FloatField()),
                ('rfcohen', models.FloatField()),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Hashtagscores',
            },
        ),
    ]
